apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-file
data:
  file: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut dignissim ut enim id vulputate. Aenean ut mattis turpis, posuere laoreet leo."
