apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: batatinhago
  labels:
    app: batatinhago
spec:
  selector:
    matchLabels:
      app: batatinhago
  replicas: 2
  template:
    metadata:
      name: "batatinhago"
      labels:
        app: "batatinhago"
    spec:
      containers:
      - name: batatinhago
        image: "hudsonvonzuben/hello-batatinha-go:latest"
